CPY_SRC_FILE += \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qmldir \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/icuiqmlapi_dummy.qml \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qmldir_rls \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/qmldir \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/modalpopupdialog.qml \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/pagebase.qml \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/qmldir_rls \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/icquickimageitem_dummy.qml \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/qmldir \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/qmldir_rls \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/icquicklineseriesitem_dummy.qml \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/icquickvalueaxisitem_dummy.qml \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/icquickparlnitem_dummy.qml \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_dyncinit_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_def.h \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_memcntr.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_bytearray.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_base64.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_logging.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_minizip.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_semaphore.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_tmrqueue.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_global.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_ipcsem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_variant.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_geom2d.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_geom2dmath.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_objcache.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_threadpool.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_object.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_stratomtbl.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_heapvectortemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_pimplprivtemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_dequetemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_semtemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_tripleobjtemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_numstatqueuetemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_stacktemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_queuetemp.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_ic_atomicint.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_base.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_errdev.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_shuffle.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_pot.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_byteorder.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_ary.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_aryftr.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_arycvt.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_arydet.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_rdftsg.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_fftsgsubrt.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_peak.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_pxgray.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_pxmono.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_ic_algor_arystats.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_sharedthreadpool_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_sysevtqthread_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_rmtobjcreator_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_rmtobjdeletor_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_rmtobjsigblocker_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_rmtcallback_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_ncstring.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_filemon.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_stdioipc.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_jotaskworker.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_vardata.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_jsonrpc2.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_appdcl_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_apptot_priv.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_eventloopbarrier.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_imagedata.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_simplefsm.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_pnomap.hpp \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_geom2dalgor.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_ic_usbstormon.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_appctrlbase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_appsettingsbase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_modmgrbase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_svcbase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_viewmodelbase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_msgbus.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_objmgr.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_confirmbus.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_ic_simpleactcaller.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_ic_datatrans_buff.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_ic_datatrans_svr.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_ic_datatrans_cli.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_ic_datatrans_rshdebase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_ic_datatrans_rshde_impl_bundle.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_ic_datatrans_rssvrbase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_ic_datatrans_rssvr_impl_bundle.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_ui_qml_api.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_qsgimtexture.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_qsgtextureprov.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_qsgrenderworker.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_quickimagedata.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_quickfborenderbase.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_qsgqtlogorender.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_quickxyseriesdata.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_ic_quickaryseriesdata.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/qxpack_ic_quickqtlogoitem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/qxpack_ic_quickimageitem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/qxpack_ic_quickqtlogoitem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/qxpack_ic_quickimageitem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/qxpack_ic_quicklineseriesitem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/qxpack_ic_quickvalueaxisitem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/qxpack_ic_quickparlnitem.hxx \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/qxpackic_all_static.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/common/qxpack_indcom_common.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/algor/qxpack_indcom_algor.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/sys/qxpack_indcom_sys.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/afw/qxpack_indcom_afw.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/net/qxpack_indcom_net.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_base/qxpack_indcom_ui_qml_base.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_control/qxpack_indcom_ui_qml_control.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/ui_qml_charts/qxpack_indcom_ui_qml_charts.pri \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/update.txt \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/readme.txt \
 
CPY_TGT_PATH += \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ \
 
CPY_TGT_FILE += \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qmldir  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/icuiqmlapi_dummy.qml  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qmldir_rls  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/qmldir  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/modalpopupdialog.qml  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/pagebase.qml  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/qmldir_rls  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/icquickimageitem_dummy.qml  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/qmldir  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/qmldir_rls  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/icquicklineseriesitem_dummy.qml  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/icquickvalueaxisitem_dummy.qml  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/icquickparlnitem_dummy.qml  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_dyncinit_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_def.h  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_memcntr.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_bytearray.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_base64.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_logging.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_minizip.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_semaphore.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_tmrqueue.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_global.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_ipcsem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_variant.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_geom2d.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_geom2dmath.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_objcache.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_threadpool.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_object.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_stratomtbl.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_heapvectortemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_pimplprivtemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_dequetemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_semtemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_tripleobjtemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_numstatqueuetemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_stacktemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_queuetemp.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_ic_atomicint.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_base.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_errdev.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_shuffle.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_pot.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_byteorder.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_ary.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_aryftr.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_arycvt.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_arydet.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_rdftsg.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_fftsgsubrt.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_peak.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_pxgray.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_pxmono.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_ic_algor_arystats.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_sharedthreadpool_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_sysevtqthread_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_rmtobjcreator_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_rmtobjdeletor_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_rmtobjsigblocker_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_rmtcallback_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_ncstring.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_filemon.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_stdioipc.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_jotaskworker.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_vardata.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_jsonrpc2.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_appdcl_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_apptot_priv.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_eventloopbarrier.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_imagedata.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_simplefsm.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_pnomap.hpp  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_geom2dalgor.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_ic_usbstormon.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_appctrlbase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_appsettingsbase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_modmgrbase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_svcbase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_viewmodelbase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_msgbus.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_objmgr.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_confirmbus.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_ic_simpleactcaller.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_ic_datatrans_buff.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_ic_datatrans_svr.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_ic_datatrans_cli.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_ic_datatrans_rshdebase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_ic_datatrans_rshde_impl_bundle.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_ic_datatrans_rssvrbase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_ic_datatrans_rssvr_impl_bundle.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_ui_qml_api.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_qsgimtexture.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_qsgtextureprov.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_qsgrenderworker.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_quickimagedata.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_quickfborenderbase.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_qsgqtlogorender.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_quickxyseriesdata.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_ic_quickaryseriesdata.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/qxpack_ic_quickqtlogoitem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/qxpack_ic_quickimageitem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/qxpack_ic_quickqtlogoitem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/qxpack_ic_quickimageitem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/qxpack_ic_quicklineseriesitem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/qxpack_ic_quickvalueaxisitem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/qxpack_ic_quickparlnitem.hxx  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom//qxpackic_all_static.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/common/qxpack_indcom_common.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/algor/qxpack_indcom_algor.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/sys/qxpack_indcom_sys.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/afw/qxpack_indcom_afw.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/net/qxpack_indcom_net.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_base/qxpack_indcom_ui_qml_base.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_control/qxpack_indcom_ui_qml_control.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom/ui_qml_charts/qxpack_indcom_ui_qml_charts.pri  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom//update.txt  \
    D:/Libraries/usb_dev/usbdev/third-part/qxpack/indcom/mkspecs/../../../qxpackic-build/qxpack/indcom//readme.txt  \
 
for ( tgt_path, CPY_TGT_PATH ) {
    ! exists( $$tgt_path ) : mkpath( $$tgt_path ) 
}
tgt_cntr = 
for ( src_file, CPY_SRC_FILE ) { 
    tgt_file = $$member( CPY_TGT_FILE, $$size( tgt_cntr )) 
    tgt_cntr += 1 
    exists( $$src_file ) { 
       message( copy $$src_file ) 
       contains( QMAKE_HOST.os, Windows ) {
           cpy_tgt_file = $$replace( tgt_file, /, \\ )
           cpy_src_file = $$replace( src_file, /, \\ )
           system( "copy $${cpy_src_file} $${cpy_tgt_file} /y ")
       } else {
           system( "\cp -rf $${src_file} $${tgt_file}" )
       }
   }
}
